name: airbnb-toronto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.20.0
  - scikit-learn>=1.0.0
  - xgboost>=1.5.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - shap>=0.40.0
  - jupyter>=1.0.0